FROM hotio/qbittorrent:latest as main-linux-arm64
RUN curl -fsSL "https://github.com/Ghost-chu/qbittorrent-nox-static/releases/download/manual-4_5_x_RC_1_2-fasthash/aarch64-qbittorrent-nox" \
    > "/app/qbittorrent-nox"

FROM hotio/qbittorrent:latest as main-linux-amd64
RUN curl -fsSL "https://github.com/Ghost-chu/qbittorrent-nox-static/releases/download/manual-4_5_x_RC_1_2-fasthash/x86_64-qbittorrent-nox" \
    > "/app/qbittorrent-nox"

FROM main-${TARGETOS}-${TARGETARCH}${TARGETVARIANT}
